/***************************************************************************
 *   Copyright (C) 2008 by Bernd Buschinski                                *
 *   b.buschinski@web.de                                                   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *
 ***************************************************************************/

#include <QApplication>
#include <QIODevice>

#include "bxml.h"

int main(int argc, char* argv[])
{
    QApplication app(argc,argv);
    BXml tXml("../level/level01","BYAVSLEVEL");
    tXml.open( QIODevice::ReadWrite );

    tXml.setGroup("global");
        tXml.writeString("bgimg","bg02.png");
        tXml.writeUInt("height", 600);
        tXml.writeUInt("width", 2048);
        tXml.writeSize("startpos", QSize(30,300));
        tXml.writeSize("shipsize", QSize(60,60));
        tXml.setGroup("hitboxes");
            tXml.writeUInt("count",3);
            tXml.writeRect("hitbox0",QRect(0,10,5,40));
            tXml.writeRect("hitbox1",QRect(5,0,45,60));
            tXml.writeRect("hitbox2",QRect(50,10,10,40));
        tXml.up();
    tXml.up();
    tXml.setGroup("objects");
        tXml.writeUInt("count",6);
        tXml.setGroup("object0");
            tXml.writeRect("size",QRect(0,549,2048,51));
            tXml.writeString("image","object0.png");
        tXml.up();
        tXml.setGroup("object1");
            tXml.writeRect("size",QRect(400,100,50,200));
            tXml.writeString("image","object1.png");
        tXml.up();
        tXml.setGroup("object2");
            tXml.writeRect("size",QRect(450,100,200,50));
            tXml.writeString("image","object2.png");
        tXml.up();
        tXml.setGroup("object3");
            tXml.writeRect("size",QRect(650,250,50,200));
            tXml.writeString("image","object3.png");
        tXml.up();
        tXml.setGroup("object4");
            tXml.writeRect("size",QRect(650,450,50,100));
            tXml.writeString("image","object1.png");
        tXml.up();
        tXml.setGroup("object5");
            tXml.writeRect("size",QRect(850,0,200,50));
            tXml.writeString("image","crap-moon.png");
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",7);
                tXml.writeRect("hitbox0",QRect(0,0,10,20));
                tXml.writeRect("hitbox1",QRect(10,0,20,35));
                tXml.writeRect("hitbox2",QRect(30,0,40,45));
                tXml.writeRect("hitbox3",QRect(70,0,60,50));
                tXml.writeRect("hitbox4",QRect(130,0,40,45));
                tXml.writeRect("hitbox5",QRect(170,0,20,35));
                tXml.writeRect("hitbox6",QRect(190,0,10,20));
            tXml.up();
        tXml.up();

//         tXml.setGroup("object6");
//             tXml.writeRect("size",QRect(1480,416,200,134));
//             tXml.writeString("image","se-house.png");
//             tXml.setGroup("hitboxes");
//                 tXml.writeUInt("count",3);
//                 tXml.writeRect("hitbox0",QRect(8,64,27,69));
//                 tXml.writeRect("hitbox1",QRect(36,0,111,133));
//                 tXml.writeRect("hitbox2",QRect(148,88,48,45));
//             tXml.up();
//         tXml.up();

    tXml.up();
    tXml.setGroup("enemies");
        tXml.writeUInt("count",31);
        tXml.setGroup("enemy0");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 800);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(800,200,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(700,275));
                tXml.writePoint("direction1",QPoint(600,300));
                tXml.writePoint("direction2",QPoint(500,275));
                tXml.writePoint("direction3",QPoint(400,200));
                tXml.writePoint("direction4",QPoint(300,125));
                tXml.writePoint("direction5",QPoint(200,100));
                tXml.writePoint("direction6",QPoint(100,125));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();
        tXml.setGroup("enemy1");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 820);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(820,200,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(720,275));
                tXml.writePoint("direction1",QPoint(620,300));
                tXml.writePoint("direction2",QPoint(520,275));
                tXml.writePoint("direction3",QPoint(420,200));
                tXml.writePoint("direction4",QPoint(320,125));
                tXml.writePoint("direction5",QPoint(220,100));
                tXml.writePoint("direction6",QPoint(120,125));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();
        tXml.setGroup("enemy2");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 840);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(840,200,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(740,275));
                tXml.writePoint("direction1",QPoint(640,300));
                tXml.writePoint("direction2",QPoint(540,275));
                tXml.writePoint("direction3",QPoint(440,200));
                tXml.writePoint("direction4",QPoint(340,125));
                tXml.writePoint("direction5",QPoint(240,100));
                tXml.writePoint("direction6",QPoint(140,125));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();
        tXml.setGroup("enemy3");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 860);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(860,200,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(760,275));
                tXml.writePoint("direction1",QPoint(660,300));
                tXml.writePoint("direction2",QPoint(560,275));
                tXml.writePoint("direction3",QPoint(460,200));
                tXml.writePoint("direction4",QPoint(360,125));
                tXml.writePoint("direction5",QPoint(260,100));
                tXml.writePoint("direction6",QPoint(160,125));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();
        tXml.setGroup("enemy4");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 880);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(880,200,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(780,275));
                tXml.writePoint("direction1",QPoint(680,300));
                tXml.writePoint("direction2",QPoint(580,275));
                tXml.writePoint("direction3",QPoint(480,200));
                tXml.writePoint("direction4",QPoint(380,125));
                tXml.writePoint("direction5",QPoint(280,100));
                tXml.writePoint("direction6",QPoint(180,125));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy5");
            tXml.writeUInt("health", 100);
            tXml.writeUInt("trigger", 940);
            tXml.writeFloat("speed", 150.0f);
            tXml.writeString("image", "enemy1.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(940,180,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(120,180));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy6");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 900);
            tXml.writeFloat("speed", 180.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 0);
            tXml.writeRect("size",QRect(100,480,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(1200,480));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(6,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy7");
            tXml.writeUInt("health", 100);
            tXml.writeUInt("trigger", 1000);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy2.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeUInt("fireinterval", 1000);
            tXml.writeRect("size",QRect(1100,180,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(200,180));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();


        tXml.setGroup("enemy8");
            tXml.writeUInt("health", 30);
            tXml.writeUInt("trigger", 1100);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy3.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1100,180,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(200,180));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",3);
                tXml.writeRect("hitbox0",QRect(0,10,5,40));
                tXml.writeRect("hitbox1",QRect(5,0,45,60));
                tXml.writeRect("hitbox2",QRect(50,10,10,40));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy9");
            tXml.writeUInt("health", 30);
            tXml.writeUInt("trigger", 1100);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy3.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1100,250,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(200,250));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",3);
                tXml.writeRect("hitbox0",QRect(0,10,5,40));
                tXml.writeRect("hitbox1",QRect(5,0,45,60));
                tXml.writeRect("hitbox2",QRect(50,10,10,40));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy10");
            tXml.writeUInt("health", 30);
            tXml.writeUInt("trigger", 1100);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy3.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1100,320,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(200,320));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",3);
                tXml.writeRect("hitbox0",QRect(0,10,5,40));
                tXml.writeRect("hitbox1",QRect(5,0,45,60));
                tXml.writeRect("hitbox2",QRect(50,10,10,40));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy11");
            tXml.writeUInt("health", 30);
            tXml.writeUInt("trigger", 1100);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy3.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1100,110,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(200,110));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",3);
                tXml.writeRect("hitbox0",QRect(0,10,5,40));
                tXml.writeRect("hitbox1",QRect(5,0,45,60));
                tXml.writeRect("hitbox2",QRect(50,10,10,40));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy12");
            tXml.writeUInt("health", 30);
            tXml.writeUInt("trigger", 1100);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy3.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1100,390,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(200,390));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",3);
                tXml.writeRect("hitbox0",QRect(0,10,5,40));
                tXml.writeRect("hitbox1",QRect(5,0,45,60));
                tXml.writeRect("hitbox2",QRect(50,10,10,40));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy13");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1150);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy2.png");
            tXml.writeUInt("imagemodifier", 0);
            tXml.writeUInt("fireinterval", 1200);
            tXml.writeRect("size",QRect(300,390,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(1500,390));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(6,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy14");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1150);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy2.png");
            tXml.writeUInt("imagemodifier", 0);
            tXml.writeUInt("fireinterval", 1200);
            tXml.writeRect("size",QRect(300,90,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(1500,90));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(6,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy15");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1220);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy1.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1220,390,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(500,90));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy16");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1220);
            tXml.writeFloat("speed", 110.0f);
            tXml.writeString("image", "enemy1.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1220,90,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(500,390));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();


        tXml.setGroup("enemy17");
            tXml.writeUInt("health", 150);
            tXml.writeUInt("trigger", 1350);
            tXml.writeFloat("speed", 80.0f);
            tXml.writeString("image", "enemy4.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1350,150,120,70));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(500,150));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",3);
                tXml.writeRect("hitbox0",QRect(0,24,36,23));
                tXml.writeRect("hitbox1",QRect(37,9,43,54));
                tXml.writeRect("hitbox2",QRect(80,0,36,69));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy18");
            tXml.writeUInt("health", 150);
            tXml.writeUInt("trigger", 1350);
            tXml.writeFloat("speed", 80.0f);
            tXml.writeString("image", "enemy4.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1350,280,120,70));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(500,280));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",3);
                tXml.writeRect("hitbox0",QRect(0,24,36,23));
                tXml.writeRect("hitbox1",QRect(37,9,43,54));
                tXml.writeRect("hitbox2",QRect(80,0,36,69));
            tXml.up();
            tXml.setGroup("item");
                tXml.writeInt("damageincrease",0);
                tXml.writeInt("firetype",1);
                tXml.writeString("image","upgrade0.png");
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy19");
            tXml.writeUInt("health", 150);
            tXml.writeUInt("trigger", 1350);
            tXml.writeFloat("speed", 80.0f);
            tXml.writeString("image", "enemy4.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(1350,410,120,70));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(500,410));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",3);
                tXml.writeRect("hitbox0",QRect(0,24,36,23));
                tXml.writeRect("hitbox1",QRect(37,9,43,54));
                tXml.writeRect("hitbox2",QRect(80,0,36,69));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy20");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1480);
            tXml.writeFloat("speed", 350.0f);
            tXml.writeString("image", "trap-moon.png");
            tXml.writeUInt("imagemodifier", 0);
            tXml.writeRect("size",QRect(1000,0,50,50));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(1000,6500));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,0,23,44));
                tXml.writeRect("hitbox1",QRect(24,0,24,28));
            tXml.up();
        tXml.up();

//! -------
        tXml.setGroup("enemy21");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1500);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(1500,300,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(1400,375));
                tXml.writePoint("direction1",QPoint(1300,400));
                tXml.writePoint("direction2",QPoint(1200,375));
                tXml.writePoint("direction3",QPoint(1100,300));
                tXml.writePoint("direction4",QPoint(1000,225));
                tXml.writePoint("direction5",QPoint(900,200));
                tXml.writePoint("direction6",QPoint(800,225));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();
        tXml.setGroup("enemy22");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1520);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(1520,300,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(1420,375));
                tXml.writePoint("direction1",QPoint(1320,400));
                tXml.writePoint("direction2",QPoint(1220,375));
                tXml.writePoint("direction3",QPoint(1120,300));
                tXml.writePoint("direction4",QPoint(1020,225));
                tXml.writePoint("direction5",QPoint(920,200));
                tXml.writePoint("direction6",QPoint(820,225));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();
        tXml.setGroup("enemy23");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1540);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(1540,300,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(1440,375));
                tXml.writePoint("direction1",QPoint(1340,400));
                tXml.writePoint("direction2",QPoint(1240,375));
                tXml.writePoint("direction3",QPoint(1140,300));
                tXml.writePoint("direction4",QPoint(1040,225));
                tXml.writePoint("direction5",QPoint(940,200));
                tXml.writePoint("direction6",QPoint(840,225));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();
        tXml.setGroup("enemy24");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1560);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(1560,300,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(1460,375));
                tXml.writePoint("direction1",QPoint(1360,400));
                tXml.writePoint("direction2",QPoint(1260,375));
                tXml.writePoint("direction3",QPoint(1160,300));
                tXml.writePoint("direction4",QPoint(1060,225));
                tXml.writePoint("direction5",QPoint(960,200));
                tXml.writePoint("direction6",QPoint(860,225));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();
        tXml.setGroup("enemy25");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1580);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 1); //mirrorX = 1
            tXml.writeRect("size",QRect(1580,300,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",7);
                tXml.writePoint("direction0",QPoint(1480,375));
                tXml.writePoint("direction1",QPoint(1380,400));
                tXml.writePoint("direction2",QPoint(1280,375));
                tXml.writePoint("direction3",QPoint(1180,300));
                tXml.writePoint("direction4",QPoint(1080,225));
                tXml.writePoint("direction5",QPoint(980,200));
                tXml.writePoint("direction6",QPoint(880,225));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();


        tXml.setGroup("enemy26");
            tXml.writeUInt("health", 50);
            tXml.writeUInt("trigger", 1540);
            tXml.writeFloat("speed", 180.0f);
            tXml.writeString("image", "enemy0.png");
            tXml.writeUInt("imagemodifier", 0);
            tXml.writeRect("size",QRect(800,480,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(2000,480));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(6,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy27");
            tXml.writeUInt("health", 100);
            tXml.writeUInt("trigger", 1600);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy2.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeUInt("fireinterval", 1000);
            tXml.writeRect("size",QRect(1600,120,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(800,120));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy28");
            tXml.writeUInt("health", 100);
            tXml.writeUInt("trigger", 1750);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy2.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeUInt("fireinterval", 1000);
            tXml.writeRect("size",QRect(1750,380,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(900,380));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy29");
            tXml.writeUInt("health", 100);
            tXml.writeUInt("trigger", 1750);
            tXml.writeFloat("speed", 160.0f);
            tXml.writeString("image", "enemy2.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeUInt("fireinterval", 1000);
            tXml.writeRect("size",QRect(1750,280,60,60));
            tXml.setGroup("direction");
                tXml.writeUInt("count",1);
                tXml.writePoint("direction0",QPoint(900,280));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,18,60,20));
                tXml.writeRect("hitbox1",QRect(30,0,23,60));
            tXml.up();
        tXml.up();

        tXml.setGroup("enemy30");
            tXml.writeUInt("health", 3000);
            tXml.writeUInt("trigger", 2046);
            tXml.writeFloat("speed", 230.0f);
            tXml.writeString("image", "enemy1.png");
            tXml.writeUInt("imagemodifier", 1);
            tXml.writeRect("size",QRect(2048,100,120,120));
            tXml.writeUInt("fireinterval", 1050);
            tXml.setGroup("direction");
                tXml.writeUInt("count",3);
                tXml.writeInt("directiontype",2);
                tXml.writePoint("direction0",QPoint(1700,20));
                tXml.writePoint("direction1",QPoint(1900,180));
                tXml.writePoint("direction2",QPoint(1500,420));
            tXml.up();
            tXml.setGroup("hitboxes");
                tXml.writeUInt("count",2);
                tXml.writeRect("hitbox0",QRect(0,36,120,39));
                tXml.writeRect("hitbox1",QRect(60,0,46,120));
            tXml.up();
        tXml.up();


    tXml.up();

    tXml.sync();

    return 0;
}
